name: LedFx
slug: ledfx
description: Real-time LED effects driven by audio
version: "1.0.9"
url: https://github.com/encrust-ace/ha-addons
startup: services
boot: auto

arch:
  - amd64
  - aarch64
  - armv7

ingress: true
ingress_port: 8888
panel_icon: mdi:led-strip

audio: true
audio_output: true

ports: {}
ports_description: {}

map:
  - config:rw
  - share:rw

options:
  clear_effects: false
  offline: false

schema:
  clear_effects: bool
  offline: bool