name: "LedFx"
description: "Audio reactive LED controller"
version: "1.0.1"
slug: "ledfx"
init: false
arch:
  - aarch64
  - amd64
startup: "application"
boot: "auto"
map:
  - config:rw
audio: true
ingress: true
ingress_port: 8888
ingress_stream: true
panel_icon: mdi:led-strip
panel_title: "LedFx"
ports:
  8888/tcp: 8888
host_network: true
options: {}
schema: {}