name: "LedFx"
version: "1.0.0"
slug: "ledfx"
description: "Official LedFx Docker Image"
url: "https://github.com/encrust-ace/ha-addons"
arch:
  - aarch64
  - amd64
  - armv7
startup: application
host_network: true
audio: true
map:
  - config:rw
args:
  - --config
  - /data
  - --open-ui
  - --host
  - 0.0.0.0