name: "LedFx"
version: "1.0.2"
slug: "ledfx"
description: "Official LedFx Docker Image"
url: "https://github.com/encrust-ace/ha-addons"
arch:
  - aarch64
  - amd64
startup: application

# ADDED: Ingress Configuration
ingress: true
ingress_port: 8888
panel_icon: mdi:led-strip
panel_title: LedFx

audio: true
map:
  - config:rw
args:
  - --config
  - /data
  - --host
  - 0.0.0.0
  - --port
  - 8888