name: "LedFx"
version: "1.0.10"
slug: "ledfx"
description: "Official LedFx Docker Image"
url: "https://github.com/encrust-ace/ha-addons"
arch:
  - aarch64
  - amd64
startup: application
host_network: true
audio: true
map:
  - config:rw